# Generated by Django 3.2.18 on 2023-03-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankLoans', '0002_bank_loan_loanfund_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='terms',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
